BW-1856 updated sentry, newrelic version
qudini/qudini-reactive pull request #250
Opened 2024-07-29 07:15 UTC by ajpachoriya

2024-07-29 12:58 UTC, jmaister requested changes

2024-07-29 12:58 UTC, jmaister commented on pom.xml
>          <newrelic-agent.sha256-checksum>f9f81a3a500460d33cf9aec6bec288e733de843730dcbf06c9656c63f598cf19</newrelic-agent.sha256-checksum>
this checksum must be updated

2024-07-29 15:00 UTC, ajpachoriya commented on pom.xml
>          <newrelic-agent.sha256-checksum>f9f81a3a500460d33cf9aec6bec288e733de843730dcbf06c9656c63f598cf19</newrelic-agent.sha256-checksum>
updated.

2024-07-29 15:01 UTC, jmaister approved these changes

2024-07-30 09:05 UTC, mohsen0 approved these changes

2024-07-30 09:11 UTC, merged